---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
suites:
  - name: nfs-test
    run_list:
      - recipe[nfs_test::default]
    includes:
      - centos-6.4
