name            'autofs'
maintainer        'University of Derby'
maintainer_email  'ai@derby.ac.uk'
description       'Configures the autofs service'
version           '0.1.5'

supports 'smartos'
supports 'solaris2'
supports 'debian'
supports 'rhel'
supports 'fedora'
