name 'autofs'
maintainer 'University of Derby'
maintainer_email 'serverteam@derby.ac.uk'
description 'Configures the autofs service'
version '2.0.1'
source_url 'https://github.com/universityofderby/chef-autofs'
issues_url 'https://github.com/universityofderby/chef-autofs/issues'

depends 'compat_resource', '~> 12.14'
depends 'chef-sugar', '~> 3.4'
depends 'line', '~> 0.6'
